# coding:utf-8
DETAIL_YOUTUBE = 'https://www.youtube.com/watch?v='
GOOGLEAPIS_KEY = 'AIzaSyBmC9uqUBlujrGiU7gTxInC33ZoSIIQBbo'
YOUTUBE_SEARCH_URL = 'https://www.googleapis.com/youtube/v3/search?q=%s&key=%s&' \
                      'part=snippet&maxResults=50&type=video&regionCode=%s&' \
                      'relevanceLanguage=%s&safeSearch=none&videoCaption=closedCaption' \
                     '&publishedAfter=%sT00:00:00Z&publishedBefore=%sT00:00:00Z' \
                     '&videoDimension=2d&videoDuration=medium'
YOUTUBE_CAPTION_URL = 'http://video.google.com/timedtext?lang=%s&v=%s'
DOWN_DIR = '/Users/whohow/videos/'
LOG_DIR = "/data/log/script/"
SEARCH_WORDS = [
    'CNN',
    'TED',
    'NBC',
    'china+daily',
    'HBO',
    'CBS',
    'yale',
    'stanford',
    'oxford',
    'mit',
    'new+york',
    'Animal',
    'Philosophy',
    'Art',
    'History',
    'Biology',
    'literature',
    'Physics',
    'ethic',
    'Environmental+Science',
    'Chemistry',
    'Sociology',
    'Administration',
    'Law',
    'Economics',
    'speech',
    'Medical+Science',
    'media',
    'Skill',
    'Psychology',
    'science+and+technology',
    'Military',
    'education',
    'Healthy',
    'Mathematics',
    'The+workplace',
    'Politics',
    'motion',
    'language',
    'Music',
    'Tourism',
    'Pet',
    'Culture',
    'children',
    'engineering',
    'Architecture',
    'Delicious+food',
    'Design',
    'character',
    'Internet',
    'Computer',
    'Documentary',
    'Cold+knowledge',
    'Interest',
    'Polular+Science',
    'Life+style',
    'earth',
    'science',
    'perform',
    'Art',
    'film',
    'TV+program',
    'documentary+program',
    'factual+program',
    'game+shows',
    'music+video+shows',
    'real+shows',
    'sitcoms',
    'soap+operas',
    'sports+programs',
    'talk+show',
    'variety+shows',
    'Comedy',
    'Adventure',
    'Fantasy',
    'Mystery',
    'Thriller',
    'Documentary',
    'War',
    'Western',
    'Romance',
    'Drama',
    'Horror',
    'Action',
    'Sci-Fi',
    'Music',
    'Crime'
]
